//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace NuvTools.Payment.Omie.ApiClient.Resources;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Fields
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Fields()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Payment.Omie.ApiClient.Resources.Fields", typeof(Fields).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ConsultarCliente.
    /// </summary>
    internal static string ConsultClient
    {
        get
        {
            return ResourceManager.GetString("ConsultClient", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ConsultarCadastroServico.
    /// </summary>
    internal static string ConsultServiceRegistration
    {
        get
        {
            return ResourceManager.GetString("ConsultServiceRegistration", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to IncluirOS.
    /// </summary>
    internal static string IncludeOS
    {
        get
        {
            return ResourceManager.GetString("IncludeOS", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to GerarBoleto.
    /// </summary>
    internal static string GenerateBillet
    {
        get
        {
            return ResourceManager.GetString("GenerateBillet", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to IncluirContaReceber.
    /// </summary>
    internal static string IncludeReceivable
    {
        get
        {
            return ResourceManager.GetString("IncludeReceivable", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ObterBoleto.
    /// </summary>
    internal static string GetBillet
    {
        get
        {
            return ResourceManager.GetString("GetBillet", resourceCulture)!;
        }
    }
}
