//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace NuvTools.Payment.Omie.ApiClient.Resources;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Messages
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Messages()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Payment.Omie.ApiClient.Resources.Messages", typeof(Messages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Falha na comunicação {0}..
    /// </summary>
    internal static string FailedCommunicationX
    {
        get
        {
            return ResourceManager.GetString("FailedCommunicationX", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ao consultar cliente Omie.
    /// </summary>
    internal static string WhenConsultingOmieClient
    {
        get
        {
            return ResourceManager.GetString("WhenConsultingOmieClient", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ao consultar serviço Omie.
    /// </summary>
    internal static string WhenConsultingOmieService
    {
        get
        {
            return ResourceManager.GetString("WhenConsultingOmieService", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ao incluir ordem de serviço Omie.
    /// </summary>
    internal static string WhenIncludingOmieWorkOrder
    {
        get
        {
            return ResourceManager.GetString("WhenIncludingOmieWorkOrder", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ao faturar ordem de serviço Omie.
    /// </summary>
    internal static string WhenInvoicingOmieServiceOrder
    {
        get
        {
            return ResourceManager.GetString("WhenInvoicingOmieServiceOrder", resourceCulture)!;
        }
    }
}
