//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace NuvTools.Payment.Omie.ApiClient.Resources;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Messages
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Messages()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Payment.Omie.ApiClient.Resources.Messages", typeof(Messages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Communication failure {0}..
    /// </summary>
    internal static string FailedCommunicationX
    {
        get
        {
            return ResourceManager.GetString("FailedCommunicationX", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to when consulting Omie client.
    /// </summary>
    internal static string WhenConsultingOmieClient
    {
        get
        {
            return ResourceManager.GetString("WhenConsultingOmieClient", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to when consulting Omie service.
    /// </summary>
    internal static string WhenConsultingOmieService
    {
        get
        {
            return ResourceManager.GetString("WhenConsultingOmieService", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to when including Omie service order.
    /// </summary>
    internal static string WhenIncludingOmieWorkOrder
    {
        get
        {
            return ResourceManager.GetString("WhenIncludingOmieWorkOrder", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to when generating Omie billet.
    /// </summary>
    internal static string WhenGeneratingOmieBillet
    {
        get
        {
            return ResourceManager.GetString("WhenGeneratingOmieBillet", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to when including Omie receivable.
    /// </summary>
    internal static string WhenIncludingOmieReceivable
    {
        get
        {
            return ResourceManager.GetString("WhenIncludingOmieReceivable", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to when retrieving Omie billet.
    /// </summary>
    internal static string WhenGettingOmieBillet
    {
        get
        {
            return ResourceManager.GetString("WhenGettingOmieBillet", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Invalid response from Omie API ({0}).
    /// </summary>
    internal static string InvalidResponseFromOmieX
    {
        get
        {
            return ResourceManager.GetString("InvalidResponseFromOmieX", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Provide nCodTitulo or cCodIntTitulo.
    /// </summary>
    internal static string ProvideTituloIdentifier
    {
        get
        {
            return ResourceManager.GetString("ProvideTituloIdentifier", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Omie returned status {0} without description...
    /// </summary>
    internal static string OmieReturnedStatusXWithoutDescription
    {
        get
        {
            return ResourceManager.GetString("OmieReturnedStatusXWithoutDescription", resourceCulture)!;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Unknown error from Omie API.
    /// </summary>
    internal static string UnknownErrorFromOmie
    {
        get
        {
            return ResourceManager.GetString("UnknownErrorFromOmie", resourceCulture)!;
        }
    }
}
