//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuvTools.Payment.Omie.ApiClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuvTools.Payment.Omie.ApiClient.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure {0}..
        /// </summary>
        public static string FailedCommunicationX {
            get {
                return ResourceManager.GetString("FailedCommunicationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from Omie API ({0})..
        /// </summary>
        public static string InvalidResponseFromOmieX {
            get {
                return ResourceManager.GetString("InvalidResponseFromOmieX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omie returned status {0} without description. Check the operation configuration in the Omie panel..
        /// </summary>
        public static string OmieReturnedStatusXWithoutDescription {
            get {
                return ResourceManager.GetString("OmieReturnedStatusXWithoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide nCodTitulo or cCodIntTitulo..
        /// </summary>
        public static string ProvideTituloIdentifier {
            get {
                return ResourceManager.GetString("ProvideTituloIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error from Omie API..
        /// </summary>
        public static string UnknownErrorFromOmie {
            get {
                return ResourceManager.GetString("UnknownErrorFromOmie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when consulting Omie client.
        /// </summary>
        public static string WhenConsultingOmieClient {
            get {
                return ResourceManager.GetString("WhenConsultingOmieClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when consulting Omie service.
        /// </summary>
        public static string WhenConsultingOmieService {
            get {
                return ResourceManager.GetString("WhenConsultingOmieService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when generating Omie billet.
        /// </summary>
        public static string WhenGeneratingOmieBillet {
            get {
                return ResourceManager.GetString("WhenGeneratingOmieBillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when retrieving Omie billet.
        /// </summary>
        public static string WhenGettingOmieBillet {
            get {
                return ResourceManager.GetString("WhenGettingOmieBillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when including Omie receivable.
        /// </summary>
        public static string WhenIncludingOmieReceivable {
            get {
                return ResourceManager.GetString("WhenIncludingOmieReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when including Omie service order.
        /// </summary>
        public static string WhenIncludingOmieWorkOrder {
            get {
                return ResourceManager.GetString("WhenIncludingOmieWorkOrder", resourceCulture);
            }
        }
    }
}
